// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: IntegrationEvents/OrderStatus/event_order_status_paid.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Microsoft.eShopOnContainers.Services.Kafka.Protobuf.IntegrationEvents.OrderStatus {

  /// <summary>Holder for reflection information generated from IntegrationEvents/OrderStatus/event_order_status_paid.proto</summary>
  public static partial class EventOrderStatusPaidReflection {

    #region Descriptor
    /// <summary>File descriptor for IntegrationEvents/OrderStatus/event_order_status_paid.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EventOrderStatusPaidReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjtJbnRlZ3JhdGlvbkV2ZW50cy9PcmRlclN0YXR1cy9ldmVudF9vcmRlcl9z",
            "dGF0dXNfcGFpZC5wcm90bxI6bWljcm9zb2Z0LmVzaG9wb25jb250YWluZXJz",
            "LmludGVncmF0aW9uZXZlbnRzLm9yZGVyLnN0YXR1cxo5SW50ZWdyYXRpb25F",
            "dmVudHMvT3JkZXJTdGF0dXMvZXZlbnRfb3JkZXJpbmdfY29tbW9uLnByb3Rv",
            "IscBCh1PcmRlclN0YXR1c0NoYW5nZWRUb1BhaWRQcm90bxIQCghvcmRlcl9p",
            "ZBgBIAEoBRIUCgxvcmRlcl9zdGF0dXMYAiABKAkSEgoKYnV5ZXJfbmFtZRgD",
            "IAEoCRJqChFvcmRlcl9zdG9ja19pdGVtcxgEIAMoCzJPLm1pY3Jvc29mdC5l",
            "c2hvcG9uY29udGFpbmVycy5pbnRlZ3JhdGlvbmV2ZW50cy5vcmRlci5zdGF0",
            "dXMuT3JkZXJTdG9ja0l0ZW1Qcm90b0JUqgJRTWljcm9zb2Z0LmVTaG9wT25D",
            "b250YWluZXJzLlNlcnZpY2VzLkthZmthLlByb3RvYnVmLkludGVncmF0aW9u",
            "RXZlbnRzLk9yZGVyU3RhdHVzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Microsoft.eShopOnContainers.Services.Kafka.Protobuf.IntegrationEvents.OrderStatus.EventOrderingCommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Microsoft.eShopOnContainers.Services.Kafka.Protobuf.IntegrationEvents.OrderStatus.OrderStatusChangedToPaidProto), global::Microsoft.eShopOnContainers.Services.Kafka.Protobuf.IntegrationEvents.OrderStatus.OrderStatusChangedToPaidProto.Parser, new[]{ "OrderId", "OrderStatus", "BuyerName", "OrderStockItems" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class OrderStatusChangedToPaidProto : pb::IMessage<OrderStatusChangedToPaidProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OrderStatusChangedToPaidProto> _parser = new pb::MessageParser<OrderStatusChangedToPaidProto>(() => new OrderStatusChangedToPaidProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OrderStatusChangedToPaidProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Microsoft.eShopOnContainers.Services.Kafka.Protobuf.IntegrationEvents.OrderStatus.EventOrderStatusPaidReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderStatusChangedToPaidProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderStatusChangedToPaidProto(OrderStatusChangedToPaidProto other) : this() {
      orderId_ = other.orderId_;
      orderStatus_ = other.orderStatus_;
      buyerName_ = other.buyerName_;
      orderStockItems_ = other.orderStockItems_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderStatusChangedToPaidProto Clone() {
      return new OrderStatusChangedToPaidProto(this);
    }

    /// <summary>Field number for the "order_id" field.</summary>
    public const int OrderIdFieldNumber = 1;
    private int orderId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int OrderId {
      get { return orderId_; }
      set {
        orderId_ = value;
      }
    }

    /// <summary>Field number for the "order_status" field.</summary>
    public const int OrderStatusFieldNumber = 2;
    private string orderStatus_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OrderStatus {
      get { return orderStatus_; }
      set {
        orderStatus_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "buyer_name" field.</summary>
    public const int BuyerNameFieldNumber = 3;
    private string buyerName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BuyerName {
      get { return buyerName_; }
      set {
        buyerName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "order_stock_items" field.</summary>
    public const int OrderStockItemsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Microsoft.eShopOnContainers.Services.Kafka.Protobuf.IntegrationEvents.OrderStatus.OrderStockItemProto> _repeated_orderStockItems_codec
        = pb::FieldCodec.ForMessage(34, global::Microsoft.eShopOnContainers.Services.Kafka.Protobuf.IntegrationEvents.OrderStatus.OrderStockItemProto.Parser);
    private readonly pbc::RepeatedField<global::Microsoft.eShopOnContainers.Services.Kafka.Protobuf.IntegrationEvents.OrderStatus.OrderStockItemProto> orderStockItems_ = new pbc::RepeatedField<global::Microsoft.eShopOnContainers.Services.Kafka.Protobuf.IntegrationEvents.OrderStatus.OrderStockItemProto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Microsoft.eShopOnContainers.Services.Kafka.Protobuf.IntegrationEvents.OrderStatus.OrderStockItemProto> OrderStockItems {
      get { return orderStockItems_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OrderStatusChangedToPaidProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OrderStatusChangedToPaidProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OrderId != other.OrderId) return false;
      if (OrderStatus != other.OrderStatus) return false;
      if (BuyerName != other.BuyerName) return false;
      if(!orderStockItems_.Equals(other.orderStockItems_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (OrderId != 0) hash ^= OrderId.GetHashCode();
      if (OrderStatus.Length != 0) hash ^= OrderStatus.GetHashCode();
      if (BuyerName.Length != 0) hash ^= BuyerName.GetHashCode();
      hash ^= orderStockItems_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (OrderId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(OrderId);
      }
      if (OrderStatus.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(OrderStatus);
      }
      if (BuyerName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(BuyerName);
      }
      orderStockItems_.WriteTo(output, _repeated_orderStockItems_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (OrderId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(OrderId);
      }
      if (OrderStatus.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(OrderStatus);
      }
      if (BuyerName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(BuyerName);
      }
      orderStockItems_.WriteTo(ref output, _repeated_orderStockItems_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (OrderId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(OrderId);
      }
      if (OrderStatus.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OrderStatus);
      }
      if (BuyerName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BuyerName);
      }
      size += orderStockItems_.CalculateSize(_repeated_orderStockItems_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OrderStatusChangedToPaidProto other) {
      if (other == null) {
        return;
      }
      if (other.OrderId != 0) {
        OrderId = other.OrderId;
      }
      if (other.OrderStatus.Length != 0) {
        OrderStatus = other.OrderStatus;
      }
      if (other.BuyerName.Length != 0) {
        BuyerName = other.BuyerName;
      }
      orderStockItems_.Add(other.orderStockItems_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            OrderId = input.ReadInt32();
            break;
          }
          case 18: {
            OrderStatus = input.ReadString();
            break;
          }
          case 26: {
            BuyerName = input.ReadString();
            break;
          }
          case 34: {
            orderStockItems_.AddEntriesFrom(input, _repeated_orderStockItems_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            OrderId = input.ReadInt32();
            break;
          }
          case 18: {
            OrderStatus = input.ReadString();
            break;
          }
          case 26: {
            BuyerName = input.ReadString();
            break;
          }
          case 34: {
            orderStockItems_.AddEntriesFrom(ref input, _repeated_orderStockItems_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
