// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: event_ordering_compose.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents {

  /// <summary>Holder for reflection information generated from event_ordering_compose.proto</summary>
  public static partial class EventOrderingComposeReflection {

    #region Descriptor
    /// <summary>File descriptor for event_ordering_compose.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EventOrderingComposeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxldmVudF9vcmRlcmluZ19jb21wb3NlLnByb3RvGi9ldmVudF9vcmRlcmlu",
            "Z19zdGF0dXNfY2hhbmdlZF90b19hd2FpdGluZy5wcm90bxorZXZlbnRfb3Jk",
            "ZXJpbmdfc3RhdHVzX2NoYW5nZWRfdG9fcGFpZC5wcm90bxokZXZlbnRfb3Jk",
            "ZXJpbmdfc3RvY2tfY29uZmlybWVkLnByb3RvGiNldmVudF9vcmRlcmluZ19z",
            "dG9ja19yZWplY3RlZC5wcm90byLIAwoLT3JkZXJFdmVudHMSXAonb3JkZXJf",
            "c3RvY2tfY29uZmlybWVkX2ludGVncmF0aW9uX2V2ZW50GAEgASgLMikuT3Jk",
            "ZXJTdG9ja0NvbmZpcm1lZEludGVncmF0aW9uRXZlbnRQcm90b0gAEloKJm9y",
            "ZGVyX3N0b2NrX3JlamVjdGVkX2ludGVncmF0aW9uX2V2ZW50GAIgASgLMigu",
            "T3JkZXJTdG9ja1JlamVjdGVkSW50ZWdyYXRpb25FdmVudFByb3RvSAASaAou",
            "b3JkZXJfc3RhdHVzX2NoYW5nZWRfdG9fcGFpZF9pbnRlZ3JhdGlvbl9ldmVu",
            "dBgDIAEoCzIuLk9yZGVyU3RhdHVzQ2hhbmdlZFRvUGFpZEludGVncmF0aW9u",
            "RXZlbnRQcm90b0gAEoUBCj1vcmRlcl9zdGF0dXNfY2hhbmdlZF90b19hd2Fp",
            "dGluZ192YWxpZGF0aW9uX2ludGVncmF0aW9uX2V2ZW50GAQgASgLMjwuT3Jk",
            "ZXJTdGF0dXNDaGFuZ2VkVG9Bd2FpdGluZ1ZhbGlkYXRpb25JbnRlZ3JhdGlv",
            "bkV2ZW50UHJvdG9IAEINCgtvbmVvZl9vcmRlckJRqgJOTWljcm9zb2Z0LmVT",
            "aG9wT25Db250YWluZXJzLlNlcnZpY2VzLkNhdGFsb2cuQVBJLkludGVncmF0",
            "aW9uRXZlbnRzLlByb3RvRXZlbnRzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.EventOrderingStatusChangedToAwaitingReflection.Descriptor, global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.EventOrderingStatusChangedToPaidReflection.Descriptor, global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.EventOrderingStockConfirmedReflection.Descriptor, global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.EventOrderingStockRejectedReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderEvents), global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderEvents.Parser, new[]{ "OrderStockConfirmedIntegrationEvent", "OrderStockRejectedIntegrationEvent", "OrderStatusChangedToPaidIntegrationEvent", "OrderStatusChangedToAwaitingValidationIntegrationEvent" }, new[]{ "OneofOrder" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class OrderEvents : pb::IMessage<OrderEvents>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OrderEvents> _parser = new pb::MessageParser<OrderEvents>(() => new OrderEvents());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OrderEvents> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.EventOrderingComposeReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderEvents() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderEvents(OrderEvents other) : this() {
      switch (other.OneofOrderCase) {
        case OneofOrderOneofCase.OrderStockConfirmedIntegrationEvent:
          OrderStockConfirmedIntegrationEvent = other.OrderStockConfirmedIntegrationEvent.Clone();
          break;
        case OneofOrderOneofCase.OrderStockRejectedIntegrationEvent:
          OrderStockRejectedIntegrationEvent = other.OrderStockRejectedIntegrationEvent.Clone();
          break;
        case OneofOrderOneofCase.OrderStatusChangedToPaidIntegrationEvent:
          OrderStatusChangedToPaidIntegrationEvent = other.OrderStatusChangedToPaidIntegrationEvent.Clone();
          break;
        case OneofOrderOneofCase.OrderStatusChangedToAwaitingValidationIntegrationEvent:
          OrderStatusChangedToAwaitingValidationIntegrationEvent = other.OrderStatusChangedToAwaitingValidationIntegrationEvent.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderEvents Clone() {
      return new OrderEvents(this);
    }

    /// <summary>Field number for the "order_stock_confirmed_integration_event" field.</summary>
    public const int OrderStockConfirmedIntegrationEventFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockConfirmedIntegrationEventProto OrderStockConfirmedIntegrationEvent {
      get { return oneofOrderCase_ == OneofOrderOneofCase.OrderStockConfirmedIntegrationEvent ? (global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockConfirmedIntegrationEventProto) oneofOrder_ : null; }
      set {
        oneofOrder_ = value;
        oneofOrderCase_ = value == null ? OneofOrderOneofCase.None : OneofOrderOneofCase.OrderStockConfirmedIntegrationEvent;
      }
    }

    /// <summary>Field number for the "order_stock_rejected_integration_event" field.</summary>
    public const int OrderStockRejectedIntegrationEventFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockRejectedIntegrationEventProto OrderStockRejectedIntegrationEvent {
      get { return oneofOrderCase_ == OneofOrderOneofCase.OrderStockRejectedIntegrationEvent ? (global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockRejectedIntegrationEventProto) oneofOrder_ : null; }
      set {
        oneofOrder_ = value;
        oneofOrderCase_ = value == null ? OneofOrderOneofCase.None : OneofOrderOneofCase.OrderStockRejectedIntegrationEvent;
      }
    }

    /// <summary>Field number for the "order_status_changed_to_paid_integration_event" field.</summary>
    public const int OrderStatusChangedToPaidIntegrationEventFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStatusChangedToPaidIntegrationEventProto OrderStatusChangedToPaidIntegrationEvent {
      get { return oneofOrderCase_ == OneofOrderOneofCase.OrderStatusChangedToPaidIntegrationEvent ? (global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStatusChangedToPaidIntegrationEventProto) oneofOrder_ : null; }
      set {
        oneofOrder_ = value;
        oneofOrderCase_ = value == null ? OneofOrderOneofCase.None : OneofOrderOneofCase.OrderStatusChangedToPaidIntegrationEvent;
      }
    }

    /// <summary>Field number for the "order_status_changed_to_awaiting_validation_integration_event" field.</summary>
    public const int OrderStatusChangedToAwaitingValidationIntegrationEventFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStatusChangedToAwaitingValidationIntegrationEventProto OrderStatusChangedToAwaitingValidationIntegrationEvent {
      get { return oneofOrderCase_ == OneofOrderOneofCase.OrderStatusChangedToAwaitingValidationIntegrationEvent ? (global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStatusChangedToAwaitingValidationIntegrationEventProto) oneofOrder_ : null; }
      set {
        oneofOrder_ = value;
        oneofOrderCase_ = value == null ? OneofOrderOneofCase.None : OneofOrderOneofCase.OrderStatusChangedToAwaitingValidationIntegrationEvent;
      }
    }

    private object oneofOrder_;
    /// <summary>Enum of possible cases for the "oneof_order" oneof.</summary>
    public enum OneofOrderOneofCase {
      None = 0,
      OrderStockConfirmedIntegrationEvent = 1,
      OrderStockRejectedIntegrationEvent = 2,
      OrderStatusChangedToPaidIntegrationEvent = 3,
      OrderStatusChangedToAwaitingValidationIntegrationEvent = 4,
    }
    private OneofOrderOneofCase oneofOrderCase_ = OneofOrderOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OneofOrderOneofCase OneofOrderCase {
      get { return oneofOrderCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOneofOrder() {
      oneofOrderCase_ = OneofOrderOneofCase.None;
      oneofOrder_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OrderEvents);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OrderEvents other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(OrderStockConfirmedIntegrationEvent, other.OrderStockConfirmedIntegrationEvent)) return false;
      if (!object.Equals(OrderStockRejectedIntegrationEvent, other.OrderStockRejectedIntegrationEvent)) return false;
      if (!object.Equals(OrderStatusChangedToPaidIntegrationEvent, other.OrderStatusChangedToPaidIntegrationEvent)) return false;
      if (!object.Equals(OrderStatusChangedToAwaitingValidationIntegrationEvent, other.OrderStatusChangedToAwaitingValidationIntegrationEvent)) return false;
      if (OneofOrderCase != other.OneofOrderCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (oneofOrderCase_ == OneofOrderOneofCase.OrderStockConfirmedIntegrationEvent) hash ^= OrderStockConfirmedIntegrationEvent.GetHashCode();
      if (oneofOrderCase_ == OneofOrderOneofCase.OrderStockRejectedIntegrationEvent) hash ^= OrderStockRejectedIntegrationEvent.GetHashCode();
      if (oneofOrderCase_ == OneofOrderOneofCase.OrderStatusChangedToPaidIntegrationEvent) hash ^= OrderStatusChangedToPaidIntegrationEvent.GetHashCode();
      if (oneofOrderCase_ == OneofOrderOneofCase.OrderStatusChangedToAwaitingValidationIntegrationEvent) hash ^= OrderStatusChangedToAwaitingValidationIntegrationEvent.GetHashCode();
      hash ^= (int) oneofOrderCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (oneofOrderCase_ == OneofOrderOneofCase.OrderStockConfirmedIntegrationEvent) {
        output.WriteRawTag(10);
        output.WriteMessage(OrderStockConfirmedIntegrationEvent);
      }
      if (oneofOrderCase_ == OneofOrderOneofCase.OrderStockRejectedIntegrationEvent) {
        output.WriteRawTag(18);
        output.WriteMessage(OrderStockRejectedIntegrationEvent);
      }
      if (oneofOrderCase_ == OneofOrderOneofCase.OrderStatusChangedToPaidIntegrationEvent) {
        output.WriteRawTag(26);
        output.WriteMessage(OrderStatusChangedToPaidIntegrationEvent);
      }
      if (oneofOrderCase_ == OneofOrderOneofCase.OrderStatusChangedToAwaitingValidationIntegrationEvent) {
        output.WriteRawTag(34);
        output.WriteMessage(OrderStatusChangedToAwaitingValidationIntegrationEvent);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (oneofOrderCase_ == OneofOrderOneofCase.OrderStockConfirmedIntegrationEvent) {
        output.WriteRawTag(10);
        output.WriteMessage(OrderStockConfirmedIntegrationEvent);
      }
      if (oneofOrderCase_ == OneofOrderOneofCase.OrderStockRejectedIntegrationEvent) {
        output.WriteRawTag(18);
        output.WriteMessage(OrderStockRejectedIntegrationEvent);
      }
      if (oneofOrderCase_ == OneofOrderOneofCase.OrderStatusChangedToPaidIntegrationEvent) {
        output.WriteRawTag(26);
        output.WriteMessage(OrderStatusChangedToPaidIntegrationEvent);
      }
      if (oneofOrderCase_ == OneofOrderOneofCase.OrderStatusChangedToAwaitingValidationIntegrationEvent) {
        output.WriteRawTag(34);
        output.WriteMessage(OrderStatusChangedToAwaitingValidationIntegrationEvent);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (oneofOrderCase_ == OneofOrderOneofCase.OrderStockConfirmedIntegrationEvent) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OrderStockConfirmedIntegrationEvent);
      }
      if (oneofOrderCase_ == OneofOrderOneofCase.OrderStockRejectedIntegrationEvent) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OrderStockRejectedIntegrationEvent);
      }
      if (oneofOrderCase_ == OneofOrderOneofCase.OrderStatusChangedToPaidIntegrationEvent) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OrderStatusChangedToPaidIntegrationEvent);
      }
      if (oneofOrderCase_ == OneofOrderOneofCase.OrderStatusChangedToAwaitingValidationIntegrationEvent) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OrderStatusChangedToAwaitingValidationIntegrationEvent);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OrderEvents other) {
      if (other == null) {
        return;
      }
      switch (other.OneofOrderCase) {
        case OneofOrderOneofCase.OrderStockConfirmedIntegrationEvent:
          if (OrderStockConfirmedIntegrationEvent == null) {
            OrderStockConfirmedIntegrationEvent = new global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockConfirmedIntegrationEventProto();
          }
          OrderStockConfirmedIntegrationEvent.MergeFrom(other.OrderStockConfirmedIntegrationEvent);
          break;
        case OneofOrderOneofCase.OrderStockRejectedIntegrationEvent:
          if (OrderStockRejectedIntegrationEvent == null) {
            OrderStockRejectedIntegrationEvent = new global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockRejectedIntegrationEventProto();
          }
          OrderStockRejectedIntegrationEvent.MergeFrom(other.OrderStockRejectedIntegrationEvent);
          break;
        case OneofOrderOneofCase.OrderStatusChangedToPaidIntegrationEvent:
          if (OrderStatusChangedToPaidIntegrationEvent == null) {
            OrderStatusChangedToPaidIntegrationEvent = new global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStatusChangedToPaidIntegrationEventProto();
          }
          OrderStatusChangedToPaidIntegrationEvent.MergeFrom(other.OrderStatusChangedToPaidIntegrationEvent);
          break;
        case OneofOrderOneofCase.OrderStatusChangedToAwaitingValidationIntegrationEvent:
          if (OrderStatusChangedToAwaitingValidationIntegrationEvent == null) {
            OrderStatusChangedToAwaitingValidationIntegrationEvent = new global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStatusChangedToAwaitingValidationIntegrationEventProto();
          }
          OrderStatusChangedToAwaitingValidationIntegrationEvent.MergeFrom(other.OrderStatusChangedToAwaitingValidationIntegrationEvent);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockConfirmedIntegrationEventProto subBuilder = new global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockConfirmedIntegrationEventProto();
            if (oneofOrderCase_ == OneofOrderOneofCase.OrderStockConfirmedIntegrationEvent) {
              subBuilder.MergeFrom(OrderStockConfirmedIntegrationEvent);
            }
            input.ReadMessage(subBuilder);
            OrderStockConfirmedIntegrationEvent = subBuilder;
            break;
          }
          case 18: {
            global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockRejectedIntegrationEventProto subBuilder = new global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockRejectedIntegrationEventProto();
            if (oneofOrderCase_ == OneofOrderOneofCase.OrderStockRejectedIntegrationEvent) {
              subBuilder.MergeFrom(OrderStockRejectedIntegrationEvent);
            }
            input.ReadMessage(subBuilder);
            OrderStockRejectedIntegrationEvent = subBuilder;
            break;
          }
          case 26: {
            global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStatusChangedToPaidIntegrationEventProto subBuilder = new global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStatusChangedToPaidIntegrationEventProto();
            if (oneofOrderCase_ == OneofOrderOneofCase.OrderStatusChangedToPaidIntegrationEvent) {
              subBuilder.MergeFrom(OrderStatusChangedToPaidIntegrationEvent);
            }
            input.ReadMessage(subBuilder);
            OrderStatusChangedToPaidIntegrationEvent = subBuilder;
            break;
          }
          case 34: {
            global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStatusChangedToAwaitingValidationIntegrationEventProto subBuilder = new global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStatusChangedToAwaitingValidationIntegrationEventProto();
            if (oneofOrderCase_ == OneofOrderOneofCase.OrderStatusChangedToAwaitingValidationIntegrationEvent) {
              subBuilder.MergeFrom(OrderStatusChangedToAwaitingValidationIntegrationEvent);
            }
            input.ReadMessage(subBuilder);
            OrderStatusChangedToAwaitingValidationIntegrationEvent = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockConfirmedIntegrationEventProto subBuilder = new global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockConfirmedIntegrationEventProto();
            if (oneofOrderCase_ == OneofOrderOneofCase.OrderStockConfirmedIntegrationEvent) {
              subBuilder.MergeFrom(OrderStockConfirmedIntegrationEvent);
            }
            input.ReadMessage(subBuilder);
            OrderStockConfirmedIntegrationEvent = subBuilder;
            break;
          }
          case 18: {
            global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockRejectedIntegrationEventProto subBuilder = new global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockRejectedIntegrationEventProto();
            if (oneofOrderCase_ == OneofOrderOneofCase.OrderStockRejectedIntegrationEvent) {
              subBuilder.MergeFrom(OrderStockRejectedIntegrationEvent);
            }
            input.ReadMessage(subBuilder);
            OrderStockRejectedIntegrationEvent = subBuilder;
            break;
          }
          case 26: {
            global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStatusChangedToPaidIntegrationEventProto subBuilder = new global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStatusChangedToPaidIntegrationEventProto();
            if (oneofOrderCase_ == OneofOrderOneofCase.OrderStatusChangedToPaidIntegrationEvent) {
              subBuilder.MergeFrom(OrderStatusChangedToPaidIntegrationEvent);
            }
            input.ReadMessage(subBuilder);
            OrderStatusChangedToPaidIntegrationEvent = subBuilder;
            break;
          }
          case 34: {
            global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStatusChangedToAwaitingValidationIntegrationEventProto subBuilder = new global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStatusChangedToAwaitingValidationIntegrationEventProto();
            if (oneofOrderCase_ == OneofOrderOneofCase.OrderStatusChangedToAwaitingValidationIntegrationEvent) {
              subBuilder.MergeFrom(OrderStatusChangedToAwaitingValidationIntegrationEvent);
            }
            input.ReadMessage(subBuilder);
            OrderStatusChangedToAwaitingValidationIntegrationEvent = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
