// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: integration_events.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents {

  /// <summary>Holder for reflection information generated from integration_events.proto</summary>
  public static partial class IntegrationEventsReflection {

    #region Descriptor
    /// <summary>File descriptor for integration_events.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static IntegrationEventsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhpbnRlZ3JhdGlvbl9ldmVudHMucHJvdG8aEmN1c3RvbV90eXBlcy5wcm90",
            "byKaAQooUHJvZHVjdFByaWNlQ2hhbmdlZEludGVncmF0aW9uRXZlbnRQcm90",
            "bxISCgpwcm9kdWN0X2lkGAEgASgFEiwKCW5ld19wcmljZRgCIAEoCzIZLkN1",
            "c3RvbVR5cGVzLkRlY2ltYWxWYWx1ZRIsCglvbGRfcHJpY2UYAyABKAsyGS5D",
            "dXN0b21UeXBlcy5EZWNpbWFsVmFsdWUiMwoOT3JkZXJTdG9ja0l0ZW0SEgoK",
            "cHJvZHVjdF9pZBgBIAEoBRINCgV1bml0cxgCIAEoBSJFChxDb25maXJtZWRP",
            "cmRlclN0b2NrSXRlbVByb3RvEhIKCnByb2R1Y3RfaWQYASABKAUSEQoJaGFz",
            "X3N0b2NrGAIgASgIInUKJ09yZGVyU3RvY2tSZWplY3RlZEludGVncmF0aW9u",
            "RXZlbnRQcm90bxIQCghvcmRlcl9pZBgBIAEoBRI4ChFvcmRlcl9zdG9ja19p",
            "dGVtcxgCIAMoCzIdLkNvbmZpcm1lZE9yZGVyU3RvY2tJdGVtUHJvdG8iPAoo",
            "T3JkZXJTdG9ja0NvbmZpcm1lZEludGVncmF0aW9uRXZlbnRQcm90bxIQCghv",
            "cmRlcl9pZBgBIAEoBSJtCi1PcmRlclN0YXR1c0NoYW5nZWRUb1BhaWRJbnRl",
            "Z3JhdGlvbkV2ZW50UHJvdG8SEAoIb3JkZXJfaWQYASABKAUSKgoRb3JkZXJf",
            "c3RvY2tfaXRlbXMYAiADKAsyDy5PcmRlclN0b2NrSXRlbSJ7CjtPcmRlclN0",
            "YXR1c0NoYW5nZWRUb0F3YWl0aW5nVmFsaWRhdGlvbkludGVncmF0aW9uRXZl",
            "bnRQcm90bxIQCghvcmRlcl9pZBgBIAEoBRIqChFvcmRlcl9zdG9ja19pdGVt",
            "cxgCIAMoCzIPLk9yZGVyU3RvY2tJdGVtIsgDCgtPcmRlckV2ZW50cxJcCidv",
            "cmRlcl9zdG9ja19jb25maXJtZWRfaW50ZWdyYXRpb25fZXZlbnQYASABKAsy",
            "KS5PcmRlclN0b2NrQ29uZmlybWVkSW50ZWdyYXRpb25FdmVudFByb3RvSAAS",
            "Wgomb3JkZXJfc3RvY2tfcmVqZWN0ZWRfaW50ZWdyYXRpb25fZXZlbnQYAiAB",
            "KAsyKC5PcmRlclN0b2NrUmVqZWN0ZWRJbnRlZ3JhdGlvbkV2ZW50UHJvdG9I",
            "ABJoCi5vcmRlcl9zdGF0dXNfY2hhbmdlZF90b19wYWlkX2ludGVncmF0aW9u",
            "X2V2ZW50GAMgASgLMi4uT3JkZXJTdGF0dXNDaGFuZ2VkVG9QYWlkSW50ZWdy",
            "YXRpb25FdmVudFByb3RvSAAShQEKPW9yZGVyX3N0YXR1c19jaGFuZ2VkX3Rv",
            "X2F3YWl0aW5nX3ZhbGlkYXRpb25faW50ZWdyYXRpb25fZXZlbnQYBCABKAsy",
            "PC5PcmRlclN0YXR1c0NoYW5nZWRUb0F3YWl0aW5nVmFsaWRhdGlvbkludGVn",
            "cmF0aW9uRXZlbnRQcm90b0gAQg0KC29uZW9mX29yZGVyQlGqAk5NaWNyb3Nv",
            "ZnQuZVNob3BPbkNvbnRhaW5lcnMuU2VydmljZXMuQ2F0YWxvZy5BUEkuSW50",
            "ZWdyYXRpb25FdmVudHMuUHJvdG9FdmVudHNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Services.Common.CustomTypesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.ProductPriceChangedIntegrationEventProto), global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.ProductPriceChangedIntegrationEventProto.Parser, new[]{ "ProductId", "NewPrice", "OldPrice" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockItem), global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockItem.Parser, new[]{ "ProductId", "Units" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.ConfirmedOrderStockItemProto), global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.ConfirmedOrderStockItemProto.Parser, new[]{ "ProductId", "HasStock" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockRejectedIntegrationEventProto), global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockRejectedIntegrationEventProto.Parser, new[]{ "OrderId", "OrderStockItems" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockConfirmedIntegrationEventProto), global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockConfirmedIntegrationEventProto.Parser, new[]{ "OrderId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStatusChangedToPaidIntegrationEventProto), global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStatusChangedToPaidIntegrationEventProto.Parser, new[]{ "OrderId", "OrderStockItems" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStatusChangedToAwaitingValidationIntegrationEventProto), global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStatusChangedToAwaitingValidationIntegrationEventProto.Parser, new[]{ "OrderId", "OrderStockItems" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderEvents), global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderEvents.Parser, new[]{ "OrderStockConfirmedIntegrationEvent", "OrderStockRejectedIntegrationEvent", "OrderStatusChangedToPaidIntegrationEvent", "OrderStatusChangedToAwaitingValidationIntegrationEvent" }, new[]{ "OneofOrder" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ProductPriceChangedIntegrationEventProto : pb::IMessage<ProductPriceChangedIntegrationEventProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProductPriceChangedIntegrationEventProto> _parser = new pb::MessageParser<ProductPriceChangedIntegrationEventProto>(() => new ProductPriceChangedIntegrationEventProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProductPriceChangedIntegrationEventProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.IntegrationEventsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProductPriceChangedIntegrationEventProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProductPriceChangedIntegrationEventProto(ProductPriceChangedIntegrationEventProto other) : this() {
      productId_ = other.productId_;
      newPrice_ = other.newPrice_ != null ? other.newPrice_.Clone() : null;
      oldPrice_ = other.oldPrice_ != null ? other.oldPrice_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProductPriceChangedIntegrationEventProto Clone() {
      return new ProductPriceChangedIntegrationEventProto(this);
    }

    /// <summary>Field number for the "product_id" field.</summary>
    public const int ProductIdFieldNumber = 1;
    private int productId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ProductId {
      get { return productId_; }
      set {
        productId_ = value;
      }
    }

    /// <summary>Field number for the "new_price" field.</summary>
    public const int NewPriceFieldNumber = 2;
    private global::Services.Common.DecimalValue newPrice_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Services.Common.DecimalValue NewPrice {
      get { return newPrice_; }
      set {
        newPrice_ = value;
      }
    }

    /// <summary>Field number for the "old_price" field.</summary>
    public const int OldPriceFieldNumber = 3;
    private global::Services.Common.DecimalValue oldPrice_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Services.Common.DecimalValue OldPrice {
      get { return oldPrice_; }
      set {
        oldPrice_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProductPriceChangedIntegrationEventProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProductPriceChangedIntegrationEventProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ProductId != other.ProductId) return false;
      if (!object.Equals(NewPrice, other.NewPrice)) return false;
      if (!object.Equals(OldPrice, other.OldPrice)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ProductId != 0) hash ^= ProductId.GetHashCode();
      if (newPrice_ != null) hash ^= NewPrice.GetHashCode();
      if (oldPrice_ != null) hash ^= OldPrice.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ProductId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ProductId);
      }
      if (newPrice_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(NewPrice);
      }
      if (oldPrice_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(OldPrice);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ProductId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ProductId);
      }
      if (newPrice_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(NewPrice);
      }
      if (oldPrice_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(OldPrice);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ProductId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ProductId);
      }
      if (newPrice_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NewPrice);
      }
      if (oldPrice_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OldPrice);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProductPriceChangedIntegrationEventProto other) {
      if (other == null) {
        return;
      }
      if (other.ProductId != 0) {
        ProductId = other.ProductId;
      }
      if (other.newPrice_ != null) {
        if (newPrice_ == null) {
          NewPrice = new global::Services.Common.DecimalValue();
        }
        NewPrice.MergeFrom(other.NewPrice);
      }
      if (other.oldPrice_ != null) {
        if (oldPrice_ == null) {
          OldPrice = new global::Services.Common.DecimalValue();
        }
        OldPrice.MergeFrom(other.OldPrice);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ProductId = input.ReadInt32();
            break;
          }
          case 18: {
            if (newPrice_ == null) {
              NewPrice = new global::Services.Common.DecimalValue();
            }
            input.ReadMessage(NewPrice);
            break;
          }
          case 26: {
            if (oldPrice_ == null) {
              OldPrice = new global::Services.Common.DecimalValue();
            }
            input.ReadMessage(OldPrice);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ProductId = input.ReadInt32();
            break;
          }
          case 18: {
            if (newPrice_ == null) {
              NewPrice = new global::Services.Common.DecimalValue();
            }
            input.ReadMessage(NewPrice);
            break;
          }
          case 26: {
            if (oldPrice_ == null) {
              OldPrice = new global::Services.Common.DecimalValue();
            }
            input.ReadMessage(OldPrice);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class OrderStockItem : pb::IMessage<OrderStockItem>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OrderStockItem> _parser = new pb::MessageParser<OrderStockItem>(() => new OrderStockItem());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OrderStockItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.IntegrationEventsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderStockItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderStockItem(OrderStockItem other) : this() {
      productId_ = other.productId_;
      units_ = other.units_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderStockItem Clone() {
      return new OrderStockItem(this);
    }

    /// <summary>Field number for the "product_id" field.</summary>
    public const int ProductIdFieldNumber = 1;
    private int productId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ProductId {
      get { return productId_; }
      set {
        productId_ = value;
      }
    }

    /// <summary>Field number for the "units" field.</summary>
    public const int UnitsFieldNumber = 2;
    private int units_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Units {
      get { return units_; }
      set {
        units_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OrderStockItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OrderStockItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ProductId != other.ProductId) return false;
      if (Units != other.Units) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ProductId != 0) hash ^= ProductId.GetHashCode();
      if (Units != 0) hash ^= Units.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ProductId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ProductId);
      }
      if (Units != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Units);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ProductId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ProductId);
      }
      if (Units != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Units);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ProductId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ProductId);
      }
      if (Units != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Units);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OrderStockItem other) {
      if (other == null) {
        return;
      }
      if (other.ProductId != 0) {
        ProductId = other.ProductId;
      }
      if (other.Units != 0) {
        Units = other.Units;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ProductId = input.ReadInt32();
            break;
          }
          case 16: {
            Units = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ProductId = input.ReadInt32();
            break;
          }
          case 16: {
            Units = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ConfirmedOrderStockItemProto : pb::IMessage<ConfirmedOrderStockItemProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ConfirmedOrderStockItemProto> _parser = new pb::MessageParser<ConfirmedOrderStockItemProto>(() => new ConfirmedOrderStockItemProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ConfirmedOrderStockItemProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.IntegrationEventsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConfirmedOrderStockItemProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConfirmedOrderStockItemProto(ConfirmedOrderStockItemProto other) : this() {
      productId_ = other.productId_;
      hasStock_ = other.hasStock_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConfirmedOrderStockItemProto Clone() {
      return new ConfirmedOrderStockItemProto(this);
    }

    /// <summary>Field number for the "product_id" field.</summary>
    public const int ProductIdFieldNumber = 1;
    private int productId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ProductId {
      get { return productId_; }
      set {
        productId_ = value;
      }
    }

    /// <summary>Field number for the "has_stock" field.</summary>
    public const int HasStockFieldNumber = 2;
    private bool hasStock_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasStock {
      get { return hasStock_; }
      set {
        hasStock_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ConfirmedOrderStockItemProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ConfirmedOrderStockItemProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ProductId != other.ProductId) return false;
      if (HasStock != other.HasStock) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ProductId != 0) hash ^= ProductId.GetHashCode();
      if (HasStock != false) hash ^= HasStock.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ProductId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ProductId);
      }
      if (HasStock != false) {
        output.WriteRawTag(16);
        output.WriteBool(HasStock);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ProductId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ProductId);
      }
      if (HasStock != false) {
        output.WriteRawTag(16);
        output.WriteBool(HasStock);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ProductId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ProductId);
      }
      if (HasStock != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ConfirmedOrderStockItemProto other) {
      if (other == null) {
        return;
      }
      if (other.ProductId != 0) {
        ProductId = other.ProductId;
      }
      if (other.HasStock != false) {
        HasStock = other.HasStock;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ProductId = input.ReadInt32();
            break;
          }
          case 16: {
            HasStock = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ProductId = input.ReadInt32();
            break;
          }
          case 16: {
            HasStock = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class OrderStockRejectedIntegrationEventProto : pb::IMessage<OrderStockRejectedIntegrationEventProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OrderStockRejectedIntegrationEventProto> _parser = new pb::MessageParser<OrderStockRejectedIntegrationEventProto>(() => new OrderStockRejectedIntegrationEventProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OrderStockRejectedIntegrationEventProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.IntegrationEventsReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderStockRejectedIntegrationEventProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderStockRejectedIntegrationEventProto(OrderStockRejectedIntegrationEventProto other) : this() {
      orderId_ = other.orderId_;
      orderStockItems_ = other.orderStockItems_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderStockRejectedIntegrationEventProto Clone() {
      return new OrderStockRejectedIntegrationEventProto(this);
    }

    /// <summary>Field number for the "order_id" field.</summary>
    public const int OrderIdFieldNumber = 1;
    private int orderId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int OrderId {
      get { return orderId_; }
      set {
        orderId_ = value;
      }
    }

    /// <summary>Field number for the "order_stock_items" field.</summary>
    public const int OrderStockItemsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.ConfirmedOrderStockItemProto> _repeated_orderStockItems_codec
        = pb::FieldCodec.ForMessage(18, global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.ConfirmedOrderStockItemProto.Parser);
    private readonly pbc::RepeatedField<global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.ConfirmedOrderStockItemProto> orderStockItems_ = new pbc::RepeatedField<global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.ConfirmedOrderStockItemProto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.ConfirmedOrderStockItemProto> OrderStockItems {
      get { return orderStockItems_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OrderStockRejectedIntegrationEventProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OrderStockRejectedIntegrationEventProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OrderId != other.OrderId) return false;
      if(!orderStockItems_.Equals(other.orderStockItems_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (OrderId != 0) hash ^= OrderId.GetHashCode();
      hash ^= orderStockItems_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (OrderId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(OrderId);
      }
      orderStockItems_.WriteTo(output, _repeated_orderStockItems_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (OrderId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(OrderId);
      }
      orderStockItems_.WriteTo(ref output, _repeated_orderStockItems_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (OrderId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(OrderId);
      }
      size += orderStockItems_.CalculateSize(_repeated_orderStockItems_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OrderStockRejectedIntegrationEventProto other) {
      if (other == null) {
        return;
      }
      if (other.OrderId != 0) {
        OrderId = other.OrderId;
      }
      orderStockItems_.Add(other.orderStockItems_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            OrderId = input.ReadInt32();
            break;
          }
          case 18: {
            orderStockItems_.AddEntriesFrom(input, _repeated_orderStockItems_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            OrderId = input.ReadInt32();
            break;
          }
          case 18: {
            orderStockItems_.AddEntriesFrom(ref input, _repeated_orderStockItems_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class OrderStockConfirmedIntegrationEventProto : pb::IMessage<OrderStockConfirmedIntegrationEventProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OrderStockConfirmedIntegrationEventProto> _parser = new pb::MessageParser<OrderStockConfirmedIntegrationEventProto>(() => new OrderStockConfirmedIntegrationEventProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OrderStockConfirmedIntegrationEventProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.IntegrationEventsReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderStockConfirmedIntegrationEventProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderStockConfirmedIntegrationEventProto(OrderStockConfirmedIntegrationEventProto other) : this() {
      orderId_ = other.orderId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderStockConfirmedIntegrationEventProto Clone() {
      return new OrderStockConfirmedIntegrationEventProto(this);
    }

    /// <summary>Field number for the "order_id" field.</summary>
    public const int OrderIdFieldNumber = 1;
    private int orderId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int OrderId {
      get { return orderId_; }
      set {
        orderId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OrderStockConfirmedIntegrationEventProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OrderStockConfirmedIntegrationEventProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OrderId != other.OrderId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (OrderId != 0) hash ^= OrderId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (OrderId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(OrderId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (OrderId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(OrderId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (OrderId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(OrderId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OrderStockConfirmedIntegrationEventProto other) {
      if (other == null) {
        return;
      }
      if (other.OrderId != 0) {
        OrderId = other.OrderId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            OrderId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            OrderId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class OrderStatusChangedToPaidIntegrationEventProto : pb::IMessage<OrderStatusChangedToPaidIntegrationEventProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OrderStatusChangedToPaidIntegrationEventProto> _parser = new pb::MessageParser<OrderStatusChangedToPaidIntegrationEventProto>(() => new OrderStatusChangedToPaidIntegrationEventProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OrderStatusChangedToPaidIntegrationEventProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.IntegrationEventsReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderStatusChangedToPaidIntegrationEventProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderStatusChangedToPaidIntegrationEventProto(OrderStatusChangedToPaidIntegrationEventProto other) : this() {
      orderId_ = other.orderId_;
      orderStockItems_ = other.orderStockItems_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderStatusChangedToPaidIntegrationEventProto Clone() {
      return new OrderStatusChangedToPaidIntegrationEventProto(this);
    }

    /// <summary>Field number for the "order_id" field.</summary>
    public const int OrderIdFieldNumber = 1;
    private int orderId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int OrderId {
      get { return orderId_; }
      set {
        orderId_ = value;
      }
    }

    /// <summary>Field number for the "order_stock_items" field.</summary>
    public const int OrderStockItemsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockItem> _repeated_orderStockItems_codec
        = pb::FieldCodec.ForMessage(18, global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockItem.Parser);
    private readonly pbc::RepeatedField<global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockItem> orderStockItems_ = new pbc::RepeatedField<global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockItem>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockItem> OrderStockItems {
      get { return orderStockItems_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OrderStatusChangedToPaidIntegrationEventProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OrderStatusChangedToPaidIntegrationEventProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OrderId != other.OrderId) return false;
      if(!orderStockItems_.Equals(other.orderStockItems_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (OrderId != 0) hash ^= OrderId.GetHashCode();
      hash ^= orderStockItems_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (OrderId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(OrderId);
      }
      orderStockItems_.WriteTo(output, _repeated_orderStockItems_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (OrderId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(OrderId);
      }
      orderStockItems_.WriteTo(ref output, _repeated_orderStockItems_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (OrderId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(OrderId);
      }
      size += orderStockItems_.CalculateSize(_repeated_orderStockItems_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OrderStatusChangedToPaidIntegrationEventProto other) {
      if (other == null) {
        return;
      }
      if (other.OrderId != 0) {
        OrderId = other.OrderId;
      }
      orderStockItems_.Add(other.orderStockItems_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            OrderId = input.ReadInt32();
            break;
          }
          case 18: {
            orderStockItems_.AddEntriesFrom(input, _repeated_orderStockItems_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            OrderId = input.ReadInt32();
            break;
          }
          case 18: {
            orderStockItems_.AddEntriesFrom(ref input, _repeated_orderStockItems_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class OrderStatusChangedToAwaitingValidationIntegrationEventProto : pb::IMessage<OrderStatusChangedToAwaitingValidationIntegrationEventProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OrderStatusChangedToAwaitingValidationIntegrationEventProto> _parser = new pb::MessageParser<OrderStatusChangedToAwaitingValidationIntegrationEventProto>(() => new OrderStatusChangedToAwaitingValidationIntegrationEventProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OrderStatusChangedToAwaitingValidationIntegrationEventProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.IntegrationEventsReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderStatusChangedToAwaitingValidationIntegrationEventProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderStatusChangedToAwaitingValidationIntegrationEventProto(OrderStatusChangedToAwaitingValidationIntegrationEventProto other) : this() {
      orderId_ = other.orderId_;
      orderStockItems_ = other.orderStockItems_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderStatusChangedToAwaitingValidationIntegrationEventProto Clone() {
      return new OrderStatusChangedToAwaitingValidationIntegrationEventProto(this);
    }

    /// <summary>Field number for the "order_id" field.</summary>
    public const int OrderIdFieldNumber = 1;
    private int orderId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int OrderId {
      get { return orderId_; }
      set {
        orderId_ = value;
      }
    }

    /// <summary>Field number for the "order_stock_items" field.</summary>
    public const int OrderStockItemsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockItem> _repeated_orderStockItems_codec
        = pb::FieldCodec.ForMessage(18, global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockItem.Parser);
    private readonly pbc::RepeatedField<global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockItem> orderStockItems_ = new pbc::RepeatedField<global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockItem>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockItem> OrderStockItems {
      get { return orderStockItems_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OrderStatusChangedToAwaitingValidationIntegrationEventProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OrderStatusChangedToAwaitingValidationIntegrationEventProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OrderId != other.OrderId) return false;
      if(!orderStockItems_.Equals(other.orderStockItems_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (OrderId != 0) hash ^= OrderId.GetHashCode();
      hash ^= orderStockItems_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (OrderId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(OrderId);
      }
      orderStockItems_.WriteTo(output, _repeated_orderStockItems_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (OrderId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(OrderId);
      }
      orderStockItems_.WriteTo(ref output, _repeated_orderStockItems_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (OrderId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(OrderId);
      }
      size += orderStockItems_.CalculateSize(_repeated_orderStockItems_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OrderStatusChangedToAwaitingValidationIntegrationEventProto other) {
      if (other == null) {
        return;
      }
      if (other.OrderId != 0) {
        OrderId = other.OrderId;
      }
      orderStockItems_.Add(other.orderStockItems_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            OrderId = input.ReadInt32();
            break;
          }
          case 18: {
            orderStockItems_.AddEntriesFrom(input, _repeated_orderStockItems_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            OrderId = input.ReadInt32();
            break;
          }
          case 18: {
            orderStockItems_.AddEntriesFrom(ref input, _repeated_orderStockItems_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class OrderEvents : pb::IMessage<OrderEvents>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OrderEvents> _parser = new pb::MessageParser<OrderEvents>(() => new OrderEvents());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OrderEvents> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.IntegrationEventsReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderEvents() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderEvents(OrderEvents other) : this() {
      switch (other.OneofOrderCase) {
        case OneofOrderOneofCase.OrderStockConfirmedIntegrationEvent:
          OrderStockConfirmedIntegrationEvent = other.OrderStockConfirmedIntegrationEvent.Clone();
          break;
        case OneofOrderOneofCase.OrderStockRejectedIntegrationEvent:
          OrderStockRejectedIntegrationEvent = other.OrderStockRejectedIntegrationEvent.Clone();
          break;
        case OneofOrderOneofCase.OrderStatusChangedToPaidIntegrationEvent:
          OrderStatusChangedToPaidIntegrationEvent = other.OrderStatusChangedToPaidIntegrationEvent.Clone();
          break;
        case OneofOrderOneofCase.OrderStatusChangedToAwaitingValidationIntegrationEvent:
          OrderStatusChangedToAwaitingValidationIntegrationEvent = other.OrderStatusChangedToAwaitingValidationIntegrationEvent.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderEvents Clone() {
      return new OrderEvents(this);
    }

    /// <summary>Field number for the "order_stock_confirmed_integration_event" field.</summary>
    public const int OrderStockConfirmedIntegrationEventFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockConfirmedIntegrationEventProto OrderStockConfirmedIntegrationEvent {
      get { return oneofOrderCase_ == OneofOrderOneofCase.OrderStockConfirmedIntegrationEvent ? (global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockConfirmedIntegrationEventProto) oneofOrder_ : null; }
      set {
        oneofOrder_ = value;
        oneofOrderCase_ = value == null ? OneofOrderOneofCase.None : OneofOrderOneofCase.OrderStockConfirmedIntegrationEvent;
      }
    }

    /// <summary>Field number for the "order_stock_rejected_integration_event" field.</summary>
    public const int OrderStockRejectedIntegrationEventFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockRejectedIntegrationEventProto OrderStockRejectedIntegrationEvent {
      get { return oneofOrderCase_ == OneofOrderOneofCase.OrderStockRejectedIntegrationEvent ? (global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockRejectedIntegrationEventProto) oneofOrder_ : null; }
      set {
        oneofOrder_ = value;
        oneofOrderCase_ = value == null ? OneofOrderOneofCase.None : OneofOrderOneofCase.OrderStockRejectedIntegrationEvent;
      }
    }

    /// <summary>Field number for the "order_status_changed_to_paid_integration_event" field.</summary>
    public const int OrderStatusChangedToPaidIntegrationEventFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStatusChangedToPaidIntegrationEventProto OrderStatusChangedToPaidIntegrationEvent {
      get { return oneofOrderCase_ == OneofOrderOneofCase.OrderStatusChangedToPaidIntegrationEvent ? (global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStatusChangedToPaidIntegrationEventProto) oneofOrder_ : null; }
      set {
        oneofOrder_ = value;
        oneofOrderCase_ = value == null ? OneofOrderOneofCase.None : OneofOrderOneofCase.OrderStatusChangedToPaidIntegrationEvent;
      }
    }

    /// <summary>Field number for the "order_status_changed_to_awaiting_validation_integration_event" field.</summary>
    public const int OrderStatusChangedToAwaitingValidationIntegrationEventFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStatusChangedToAwaitingValidationIntegrationEventProto OrderStatusChangedToAwaitingValidationIntegrationEvent {
      get { return oneofOrderCase_ == OneofOrderOneofCase.OrderStatusChangedToAwaitingValidationIntegrationEvent ? (global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStatusChangedToAwaitingValidationIntegrationEventProto) oneofOrder_ : null; }
      set {
        oneofOrder_ = value;
        oneofOrderCase_ = value == null ? OneofOrderOneofCase.None : OneofOrderOneofCase.OrderStatusChangedToAwaitingValidationIntegrationEvent;
      }
    }

    private object oneofOrder_;
    /// <summary>Enum of possible cases for the "oneof_order" oneof.</summary>
    public enum OneofOrderOneofCase {
      None = 0,
      OrderStockConfirmedIntegrationEvent = 1,
      OrderStockRejectedIntegrationEvent = 2,
      OrderStatusChangedToPaidIntegrationEvent = 3,
      OrderStatusChangedToAwaitingValidationIntegrationEvent = 4,
    }
    private OneofOrderOneofCase oneofOrderCase_ = OneofOrderOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OneofOrderOneofCase OneofOrderCase {
      get { return oneofOrderCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOneofOrder() {
      oneofOrderCase_ = OneofOrderOneofCase.None;
      oneofOrder_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OrderEvents);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OrderEvents other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(OrderStockConfirmedIntegrationEvent, other.OrderStockConfirmedIntegrationEvent)) return false;
      if (!object.Equals(OrderStockRejectedIntegrationEvent, other.OrderStockRejectedIntegrationEvent)) return false;
      if (!object.Equals(OrderStatusChangedToPaidIntegrationEvent, other.OrderStatusChangedToPaidIntegrationEvent)) return false;
      if (!object.Equals(OrderStatusChangedToAwaitingValidationIntegrationEvent, other.OrderStatusChangedToAwaitingValidationIntegrationEvent)) return false;
      if (OneofOrderCase != other.OneofOrderCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (oneofOrderCase_ == OneofOrderOneofCase.OrderStockConfirmedIntegrationEvent) hash ^= OrderStockConfirmedIntegrationEvent.GetHashCode();
      if (oneofOrderCase_ == OneofOrderOneofCase.OrderStockRejectedIntegrationEvent) hash ^= OrderStockRejectedIntegrationEvent.GetHashCode();
      if (oneofOrderCase_ == OneofOrderOneofCase.OrderStatusChangedToPaidIntegrationEvent) hash ^= OrderStatusChangedToPaidIntegrationEvent.GetHashCode();
      if (oneofOrderCase_ == OneofOrderOneofCase.OrderStatusChangedToAwaitingValidationIntegrationEvent) hash ^= OrderStatusChangedToAwaitingValidationIntegrationEvent.GetHashCode();
      hash ^= (int) oneofOrderCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (oneofOrderCase_ == OneofOrderOneofCase.OrderStockConfirmedIntegrationEvent) {
        output.WriteRawTag(10);
        output.WriteMessage(OrderStockConfirmedIntegrationEvent);
      }
      if (oneofOrderCase_ == OneofOrderOneofCase.OrderStockRejectedIntegrationEvent) {
        output.WriteRawTag(18);
        output.WriteMessage(OrderStockRejectedIntegrationEvent);
      }
      if (oneofOrderCase_ == OneofOrderOneofCase.OrderStatusChangedToPaidIntegrationEvent) {
        output.WriteRawTag(26);
        output.WriteMessage(OrderStatusChangedToPaidIntegrationEvent);
      }
      if (oneofOrderCase_ == OneofOrderOneofCase.OrderStatusChangedToAwaitingValidationIntegrationEvent) {
        output.WriteRawTag(34);
        output.WriteMessage(OrderStatusChangedToAwaitingValidationIntegrationEvent);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (oneofOrderCase_ == OneofOrderOneofCase.OrderStockConfirmedIntegrationEvent) {
        output.WriteRawTag(10);
        output.WriteMessage(OrderStockConfirmedIntegrationEvent);
      }
      if (oneofOrderCase_ == OneofOrderOneofCase.OrderStockRejectedIntegrationEvent) {
        output.WriteRawTag(18);
        output.WriteMessage(OrderStockRejectedIntegrationEvent);
      }
      if (oneofOrderCase_ == OneofOrderOneofCase.OrderStatusChangedToPaidIntegrationEvent) {
        output.WriteRawTag(26);
        output.WriteMessage(OrderStatusChangedToPaidIntegrationEvent);
      }
      if (oneofOrderCase_ == OneofOrderOneofCase.OrderStatusChangedToAwaitingValidationIntegrationEvent) {
        output.WriteRawTag(34);
        output.WriteMessage(OrderStatusChangedToAwaitingValidationIntegrationEvent);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (oneofOrderCase_ == OneofOrderOneofCase.OrderStockConfirmedIntegrationEvent) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OrderStockConfirmedIntegrationEvent);
      }
      if (oneofOrderCase_ == OneofOrderOneofCase.OrderStockRejectedIntegrationEvent) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OrderStockRejectedIntegrationEvent);
      }
      if (oneofOrderCase_ == OneofOrderOneofCase.OrderStatusChangedToPaidIntegrationEvent) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OrderStatusChangedToPaidIntegrationEvent);
      }
      if (oneofOrderCase_ == OneofOrderOneofCase.OrderStatusChangedToAwaitingValidationIntegrationEvent) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OrderStatusChangedToAwaitingValidationIntegrationEvent);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OrderEvents other) {
      if (other == null) {
        return;
      }
      switch (other.OneofOrderCase) {
        case OneofOrderOneofCase.OrderStockConfirmedIntegrationEvent:
          if (OrderStockConfirmedIntegrationEvent == null) {
            OrderStockConfirmedIntegrationEvent = new global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockConfirmedIntegrationEventProto();
          }
          OrderStockConfirmedIntegrationEvent.MergeFrom(other.OrderStockConfirmedIntegrationEvent);
          break;
        case OneofOrderOneofCase.OrderStockRejectedIntegrationEvent:
          if (OrderStockRejectedIntegrationEvent == null) {
            OrderStockRejectedIntegrationEvent = new global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockRejectedIntegrationEventProto();
          }
          OrderStockRejectedIntegrationEvent.MergeFrom(other.OrderStockRejectedIntegrationEvent);
          break;
        case OneofOrderOneofCase.OrderStatusChangedToPaidIntegrationEvent:
          if (OrderStatusChangedToPaidIntegrationEvent == null) {
            OrderStatusChangedToPaidIntegrationEvent = new global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStatusChangedToPaidIntegrationEventProto();
          }
          OrderStatusChangedToPaidIntegrationEvent.MergeFrom(other.OrderStatusChangedToPaidIntegrationEvent);
          break;
        case OneofOrderOneofCase.OrderStatusChangedToAwaitingValidationIntegrationEvent:
          if (OrderStatusChangedToAwaitingValidationIntegrationEvent == null) {
            OrderStatusChangedToAwaitingValidationIntegrationEvent = new global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStatusChangedToAwaitingValidationIntegrationEventProto();
          }
          OrderStatusChangedToAwaitingValidationIntegrationEvent.MergeFrom(other.OrderStatusChangedToAwaitingValidationIntegrationEvent);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockConfirmedIntegrationEventProto subBuilder = new global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockConfirmedIntegrationEventProto();
            if (oneofOrderCase_ == OneofOrderOneofCase.OrderStockConfirmedIntegrationEvent) {
              subBuilder.MergeFrom(OrderStockConfirmedIntegrationEvent);
            }
            input.ReadMessage(subBuilder);
            OrderStockConfirmedIntegrationEvent = subBuilder;
            break;
          }
          case 18: {
            global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockRejectedIntegrationEventProto subBuilder = new global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockRejectedIntegrationEventProto();
            if (oneofOrderCase_ == OneofOrderOneofCase.OrderStockRejectedIntegrationEvent) {
              subBuilder.MergeFrom(OrderStockRejectedIntegrationEvent);
            }
            input.ReadMessage(subBuilder);
            OrderStockRejectedIntegrationEvent = subBuilder;
            break;
          }
          case 26: {
            global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStatusChangedToPaidIntegrationEventProto subBuilder = new global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStatusChangedToPaidIntegrationEventProto();
            if (oneofOrderCase_ == OneofOrderOneofCase.OrderStatusChangedToPaidIntegrationEvent) {
              subBuilder.MergeFrom(OrderStatusChangedToPaidIntegrationEvent);
            }
            input.ReadMessage(subBuilder);
            OrderStatusChangedToPaidIntegrationEvent = subBuilder;
            break;
          }
          case 34: {
            global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStatusChangedToAwaitingValidationIntegrationEventProto subBuilder = new global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStatusChangedToAwaitingValidationIntegrationEventProto();
            if (oneofOrderCase_ == OneofOrderOneofCase.OrderStatusChangedToAwaitingValidationIntegrationEvent) {
              subBuilder.MergeFrom(OrderStatusChangedToAwaitingValidationIntegrationEvent);
            }
            input.ReadMessage(subBuilder);
            OrderStatusChangedToAwaitingValidationIntegrationEvent = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockConfirmedIntegrationEventProto subBuilder = new global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockConfirmedIntegrationEventProto();
            if (oneofOrderCase_ == OneofOrderOneofCase.OrderStockConfirmedIntegrationEvent) {
              subBuilder.MergeFrom(OrderStockConfirmedIntegrationEvent);
            }
            input.ReadMessage(subBuilder);
            OrderStockConfirmedIntegrationEvent = subBuilder;
            break;
          }
          case 18: {
            global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockRejectedIntegrationEventProto subBuilder = new global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStockRejectedIntegrationEventProto();
            if (oneofOrderCase_ == OneofOrderOneofCase.OrderStockRejectedIntegrationEvent) {
              subBuilder.MergeFrom(OrderStockRejectedIntegrationEvent);
            }
            input.ReadMessage(subBuilder);
            OrderStockRejectedIntegrationEvent = subBuilder;
            break;
          }
          case 26: {
            global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStatusChangedToPaidIntegrationEventProto subBuilder = new global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStatusChangedToPaidIntegrationEventProto();
            if (oneofOrderCase_ == OneofOrderOneofCase.OrderStatusChangedToPaidIntegrationEvent) {
              subBuilder.MergeFrom(OrderStatusChangedToPaidIntegrationEvent);
            }
            input.ReadMessage(subBuilder);
            OrderStatusChangedToPaidIntegrationEvent = subBuilder;
            break;
          }
          case 34: {
            global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStatusChangedToAwaitingValidationIntegrationEventProto subBuilder = new global::Microsoft.eShopOnContainers.Services.Catalog.API.IntegrationEvents.ProtoEvents.OrderStatusChangedToAwaitingValidationIntegrationEventProto();
            if (oneofOrderCase_ == OneofOrderOneofCase.OrderStatusChangedToAwaitingValidationIntegrationEvent) {
              subBuilder.MergeFrom(OrderStatusChangedToAwaitingValidationIntegrationEvent);
            }
            input.ReadMessage(subBuilder);
            OrderStatusChangedToAwaitingValidationIntegrationEvent = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
