version: '3.4'

services:
    kafka1:
      image: 'bitnami/kafka:latest'
      ports:
        - "9092:9092"
      environment:
        # KRaft settings
        - KAFKA_ENABLE_KRAFT=yes
        - KAFKA_CFG_PROCESS_ROLES=broker,controller
        - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
        - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
        # Listeners
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092
        - KAFKA_NODE_ID=1
        - ALLOW_PLAINTEXT_LISTENER=yes
        - KAFKA_KRAFT_CLUSTER_ID=M2UwYmM2NzYwOTA3NDg4Nj
      volumes:
        - kafka1:/bitnami/kafka
    
    kafka2:
      image: 'bitnami/kafka:latest'
      environment:
        # KRaft settings
        - KAFKA_ENABLE_KRAFT=yes
        - KAFKA_CFG_PROCESS_ROLES=broker,controller
        - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
        - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
        # Listeners
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092
        - KAFKA_NODE_ID=2
        - ALLOW_PLAINTEXT_LISTENER=yes
        - KAFKA_KRAFT_CLUSTER_ID=M2UwYmM2NzYwOTA3NDg4Nj
      volumes:
        - kafka2:/bitnami/kafka
    
    kafka3:
      image: 'bitnami/kafka:latest'
      environment:
        # KRaft settings
        - KAFKA_ENABLE_KRAFT=yes
        - KAFKA_CFG_PROCESS_ROLES=broker,controller
        - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
        - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
        # Listeners
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9092
        - KAFKA_NODE_ID=3
        - ALLOW_PLAINTEXT_LISTENER=yes
        - KAFKA_KRAFT_CLUSTER_ID=M2UwYmM2NzYwOTA3NDg4Nj
      volumes:
        - kafka3:/bitnami/kafka

    kafka-schema-registry:
      image: confluentinc/cp-schema-registry:7.5.0
      depends_on:
        - kafka1
        - kafka2
        - kafka3
      ports:
        - 8085:8085
      environment:
        - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=kafka1:9092,kafka2:9092
        - SCHEMA_REGISTRY_HOST_NAME=kafka-schema-registry
        - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8085
        - SCHEMA_REGISTRY_DEBUG=true
        - KAFKA_LOG_CLEANUP_POLICY=compact
    
    ui:
      image: provectuslabs/kafka-ui:master
      ports:
        - 8081:8080
      depends_on:
        - kafka3
        - kafka2
        - kafka1
        - kafka-schema-registry
      environment:
        - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka1:9092
        - KAFKA_CLUSTERS_0_NAME=local
        - KAFKA_CLUSTERS_0_SCHEMAREGISTRY=http://kafka-schema-registry:8085
volumes:
  kafka1:
    driver: local
  kafka2:
    driver: local
  kafka3:
    driver: local